# Generated by Django 4.2.11 on 2024-03-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='nom_usuari',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
