# Generated by Django 4.2.11 on 2024-04-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0002_usuari_nom_usuari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='punts',
            field=models.IntegerField(default=10000),
        ),
    ]
