# Generated by Django 4.2.11 on 2024-05-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recompenses', '0001_initial'),
        ('usuaris', '0003_alter_usuari_punts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='recompenses',
            field=models.ManyToManyField(blank=True, related_name='recompenses_bescanviades', to='recompenses.recompensa'),
        ),
    ]
