# Generated by Django 4.1.7 on 2024-03-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomViatge', models.CharField(max_length=255)),
                ('dataInici', models.DateField()),
                ('dataFi', models.DateField(blank=True, null=True)),
                ('divisa', models.CharField(max_length=255)),
                ('pressupostTotal', models.IntegerField()),
                ('pressupostVariable', models.JSONField(default=list)),
                ('deutes', models.JSONField(default=list)),
                ('codi', models.CharField(max_length=255, unique=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viatges_creats', to='usuaris.usuari')),
                ('participants', models.ManyToManyField(related_name='viajes_on_participa', to='usuaris.usuari')),
            ],
        ),
    ]
