# Generated by Django 4.2.11 on 2024-03-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0002_usuari_nom_usuari'),
        ('viatges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viatge',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='viajes_on_participa', to='usuaris.usuari'),
        ),
    ]
