# Generated by Django 4.2.11 on 2024-03-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viatges', '0002_alter_viatge_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viatge',
            name='pressupostVariable',
            field=models.JSONField(default=dict),
        ),
    ]
