# Generated by Django 4.2.11 on 2024-04-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viatges', '0004_alter_viatge_datainici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viatge',
            name='deutes',
            field=models.JSONField(default=dict),
        ),
    ]
