# Generated by Django 4.2.11 on 2024-03-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viatges', '0003_alter_viatge_pressupostvariable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDespesa', models.CharField(max_length=255)),
                ('creador', models.CharField(max_length=255)),
                ('descripcio', models.CharField(blank=True, max_length=255, null=True)),
                ('preu', models.IntegerField()),
                ('categoria', models.CharField(choices=[('Menjar', 'Menjar'), ('Compres', 'Compres'), ('Turisme', 'Turisme'), ('Allotjament', 'Allotjament'), ('Transport', 'Transport'), ('Altres', 'Altres')], max_length=255)),
                ('dataInici', models.DateField(blank=True, null=True)),
                ('dataFi', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField()),
                ('ubicacio_lat', models.IntegerField(blank=True, null=True)),
                ('ubicacio_long', models.IntegerField(blank=True, null=True)),
                ('deutors', models.JSONField(blank=True, default=dict, null=True)),
                ('viatge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesa_viatge', to='viatges.viatge')),
            ],
        ),
    ]
