# Generated by Django 4.2.11 on 2024-03-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despeses', '0002_alter_despesa_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='ubicacio_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='ubicacio_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
