# Generated by Django 4.2.11 on 2024-03-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despeses', '0003_alter_despesa_ubicacio_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='hora',
        ),
    ]
