name: Continuous integration of the project.

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install requirements
      run: pip install -r ./BackEnd/requirements.txt
    
    - name: Tests usuaris
      run: |
        cd ./BackEnd/travudget
        export DJANGO_SETTINGS_MODULE=travudget.settings
        python ./usuaris/tests.py

    - name: Tests viatges
      run: python ./BackEnd/travudget/viatges/tests.py
